name: Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Install poetry
        run: pipx install poetry

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry

      - name: install dependencies
        run: poetry install
      - name: Run the tests
        run: python -m unittest

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: run ruff
        run: |
          pip3 install ruff
          ruff check .
          ruff format --check .
